############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Digital Lab"
url = "/DigitalLab"
weight = 2

#[[main]]
###parent = "Pages"
#name = "Team"
#url = "/authors"
#weight = 3

#[[main]]
#name = "About"
#url = "/about"
#weight = 3

[[main]]
parent = "Tutorials"
name = "Growth Quantification"
url = "/Tutorials/Rates+Yields"
weight = 4

[[main]]
parent = "Tutorials"
name = "Transfer Rates & Balances"
url = "/Tutorials/CarbonBalance"
weight = 5

[[main]]
parent = "Tutorials"
name = "Simulation of Metabolic Models"
url = "/Tutorials/GSMMSims"
weight = 6

#[[main]]
#weight = 4
#name = "Pages"

#[[main]]
#parent = "Pages"
#name = "Blog"
#url = "/blog"

#[[main]]
#parent = "Pages"
#name = "Contact"
#url = "/contact"

#[[main]]
#parent = "Pages"
#name = "Categories"
#url = "/categories"

#[[main]]
#parent = "Pages"
#name = "404 Page"
#url = "/404"


# footer menu
#[[footer]]
#name = "About"
#url = "/about"
#weight = 1

#[[main]]
#name = "Elements"
#url = "/elements"
#weight = 2

#[[footer]]
#name = "Privacy Policy"
#url = "/privacy-policy"
#weight = 3
